{% set name = "autoeft" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 655a07ac390e0f7d1a9dd84b45f9bbd7474ab7af4d9abfa0e2a47adbc985c71f


build:
  entry_points:
    - autoeft = autoeft.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - numpy >=1.18
    - packaging >=17.1
    - pydantic >=1.9,<2.dev0
    - pyyaml >=5.2
    - rich >=12.3
    - sage >=9.3
    - scipy >=1.8
    - semver >=3.0

test:
  imports:
    - autoeft

about:
  home: https://gitlab.com/auto_eft/autoeft
  summary: Automated operator construction for effective field theories.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - COPYRIGHT

extra:
  recipe-maintainers:
    - reason4u2
